apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-set-testing
spec:
  goTemplate: true
  generators:
    - pullRequest:
        github:
          owner: ppapapetrou76
          repo: gitops-certification-examples
        requeueAfterSeconds: 20
  template:
    metadata:
      name: 'myapp-{{.branch}}-{{.number}}'
    spec:
      source:
        repoURL: 'https://github.com/ppapapetrou76/gitops-certification-examples'
        targetRevision: '{{.head_sha}}'
        path: ./helm-apps/simple-chart
        helm:
          parameters:
            - name: "image.tag"
              value: "pull-{{.author}}-{{.head_sha}}"
      project: "my-project"
      destination:
        server: https://kubernetes.default.svc
        namespace: default