apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-set-testing
spec:
  goTemplate: true
  generators:
    - pullRequest:
        github:
          owner: ppapapetrou76
          repo: gitops-certification-examples
          labels:
            - preview
  template:
    metadata:
      name: 'myapp-{{ .branch }}-{{ .number }}'
      labels:
        key1: '{{ index .labels 0 }}'
    spec:
      source:
        repoURL: 'https://github.com/ppapapetrou76/gitops-certification-examples.git'
        targetRevision: '{{ .head_sha }}'
        path: helm-apps/simple-chart
        helm:
          parameters:
            - name: "image.tag"
              value: "pull-{{ .head_sha }}"
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .branch }}-{{ .number }}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
